version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - '80:80'
        depends_on:
            - app
        container_name: project_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: project_app

    db:
        image: mysql:latest
        restart: always
        volumes:
            - ./tmp/database:/var/lib/mysql
        environment:
            MYSQL_DATABASE: lardocker
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        container_name: project_db
#    postgres:
#        image: postgres:latest
#        restart: always
#        environment:
#            POSTGRES_DB: lardocker
#            POSTGRES_PASSWORD: root
#        container_name: project_postgres
#    adminer:
#        image: adminer
#        restart: always
#        ports:
#            - '8080:8080'
#        container_name: project_adminer
#        depends_on:
#            - db
#    mongodb:
#        image: mongo
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: root
#            MONGO_INITDB_ROOT_PASSWORD: root
#
#    mongo-express:
#        image: mongo-express
#        restart: unless-stopped
#        ports:
#            - '8081:8081'
#        environment:
#            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#            - ME_CONFIG_MONGODB_ADMINPASSWORD=root
#            - ME_CONFIG_MONGODB_SERVER=db
#        depends_on:
#            -   mongodb
